dependencies:
- name: mysql
  version: 0.8.2
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: mysql.enabled
- name: kube-lego
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.4.0
  condition: kube-lego.enabled
- name: nginx-ingress
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.21.0
  condition: nginx-ingress.enabled
