{{- if .Values.persistence.data.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{template "mattermost-team-edition.fullname" .}}-data
  annotations:
  {{- range $key, $value := .Values.persistence.data.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- if .Values.persistence.data.storageClass }}
{{- if (eq "-" .Values.persistence.data.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.data.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
