apiVersion: v1
kind: Service
metadata:
  name: {{ template "mattermost-team-edition.name" . }}
  labels:
    app: {{ template "mattermost-team-edition.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    app: {{ template "mattermost-team-edition.name" . }}
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{  template "mattermost-team-edition.name" . }}
  selector:
    app: {{ template "mattermost-team-edition.name" . }}
